# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "config-pipe" ]
  pull_request:
    branches: [ "config-pipe" ]

env:
  REPO_NAME: expsenseapp-api
  BRANCH_DEF: config-pipe

jobs:
  build:
    runs-on: self-hosted
    steps:      
      - name: connect and pull
        run: |
          cd ${{ secrets.WORK_DIR }} &&
          if [ ! -d 'expsenseapp-api' ]; then
            git clone -b $BRANCH_DEF git@github.com:InerxiaTI/expsenseapp-api.git;
          else
            git checkout $BRANCH_DEF
            cd expsenseapp-api && git pull origin $BRANCH_DEF;
          fi
      - name: build
        run: |
          cd ${{ secrets.WORK_DIR }} &&
          cd $REPO_NAME &&
          pwd
          sh scripts/build-docker.sh
      - name: deploy
        run: |
          cd ${{ secrets.WORK_DIR }} &&
          cd expsenseapp-api &&
          sh scripts/run-docker.sh
          
  

   
